spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: mongodb+srv://ashishspanicker:6gJWuGgzQ7s8hR4c@cluster0.pb6vbbj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: doctor_service
#      username: ashishspanicker
#      password: 6gJWuGgzQ7s8hR4c
server:
  port: 8200
logging:
  level:
#    root: WARN
    org:
      mongodb:
        driver: DEBUG
      springframework:
#        web: WARN
        data:
            core:
              MongoTemplate: DEBUG
              MongoOperations: DEBUG
  pattern:
    console: "%msg%n"

