app:
  name: Appointment Service
  description: Appointment Service
  version: 1.0.0
  base-url: /api/v1/appointment
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/appointment_service
server:
    port: 8300